apiVersion: apps/v1
kind: Deployment
metadata:
  name: pas-cloud
  labels:
    app: pas-cloud
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pas-cloud
  template:
    metadata:
      labels:
        app: pas-cloud
    spec:
      containers:
        - name: pas-cloud
          image: mcmega/pas-cloud:latest
          ports:
            - containerPort: 2005
          env:
            - name: NODE_ENV
              value: 'production'
            - name: BODY_SIZE_LIMIT
              value: '67108864'
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: pas-cloud-secrets
                  key: DATABASE_URL
            - name: JWT_ACCESS_EXPIRE
              valueFrom:
                secretKeyRef:
                  name: pas-cloud-secrets
                  key: JWT_ACCESS_EXPIRE
            - name: JWT_ACCESS_MAX_AGE
              valueFrom:
                secretKeyRef:
                  name: pas-cloud-secrets
                  key: JWT_ACCESS_MAX_AGE
            - name: JWT_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: pas-cloud-secrets
                  key: JWT_ACCESS_SECRET
            - name: JWT_REFRESH_EXPIRE
              valueFrom:
                secretKeyRef:
                  name: pas-cloud-secrets
                  key: JWT_REFRESH_EXPIRE
            - name: JWT_REFRESH_MAX_AGE
              valueFrom:
                secretKeyRef:
                  name: pas-cloud-secrets
                  key: JWT_REFRESH_MAX_AGE
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: pas-cloud-secrets
                  key: JWT_REFRESH_SECRET
          resources:
            limits:
              memory: '512Mi'
              cpu: '500m'
            requests:
              memory: '256Mi'
              cpu: '250m'
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 2005
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 2005
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: pas-cloud
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 2005
  selector:
    app: pas-cloud