version: '3.8'

services:
  pas-cloud:
    image: mcmega/pas-cloud:latest
    container_name: pas-cloud
    ports:
      - "2005:2005"
    environment:
      - NODE_ENV=production
      - BODY_SIZE_LIMIT=67108864
      - DATABASE_URL=${DATABASE_URL}
      - DOCKERHUB_USERNAME=${DOCKERHUB_USERNAME}
      - DOCKERHUB_TOKEN=${DOCKERHUB_TOKEN}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_ACCESS_EXPIRE=${JWT_ACCESS_EXPIRE}
      - JWT_ACCESS_MAX_AGE=${JWT_ACCESS_MAX_AGE}
      - JWT_REFRESH_EXPIRE=${JWT_REFRESH_EXPIRE}
      - JWT_REFRESH_MAX_AGE=${JWT_REFRESH_MAX_AGE}
      - PRODUCTION_SERVER_DEPLOY_KEY=${PRODUCTION_SERVER_DEPLOY_KEY}
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2005/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3